import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/app/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto h-screen max-w-screen-sm">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
